[package]
name = "rust-learning"
version.workspace = true
edition.workspace = true

[[bin]]
path = "src/main.rs"
name = "rust-learning"

[workspace]
members = [
    "syntaxes/*",
    "examples/*",
    "iced/*",
]

[dependencies]
rand = { workspace = true }

[workspace.package]
version = "0.3.0"
edition = "2024"

[workspace.dependencies]
rand = "0.10.2"
iced = "0.14.0"
